# This is a basic workflow to help you get started with Actions

name: Clone workflow

#Controls when the workflow will run 
on: 
  workflow_dispatch:
jobs:
  job_one:
    name: clone
    runs-on: Ubuntu-latest
    steps: 
      - name: testing
      uses: appleboy/ssh-action@master
      with:
        host: $((
